theme: jekyll-theme-minimal
title: Thomas Tendron
description: I am a first year PhD student at the Centre for Doctoral Training in Mathematics of Random Systems at the University of Oxford. 
github:
  is_project_page: false
