theme: jekyll-theme-minimal
github:
  is_project_page: false
plugins:
  - jekyll-seo-tag
permalink: home
title: Thomas Tendron
keywords: Thomas Tendron, maths, math, mathematics, CDT, random systems, Oxford, McGill
