theme: jekyll-theme-minimal
title: Thomas Tendron
description: I am a first year PhD student at the Centre for Doctoral Training in Mathematics of Random Systems at the University of Oxford. Before coming to Oxford, I completed my B.A. and M.A. in maths at McGill University. 
github:
  is_project_page: false
